[build]
  functions = "netlify/functions"
  publish = "public"

[dev]
  port = 8888
  functions = "netlify/functions"

# Netlify Functions are always available at:
#   /.netlify/functions/<functionName>
# Example: http://localhost:8888/.netlify/functions/send-email

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200